// LS-108: Security audit logging system
import { Request } from 'express';
import { storage } from './storage';

export type AuditAction = 
  | 'LOGIN' | 'LOGOUT' | 'LOGIN_FAILED'
  | 'PROFILE_UPDATE' | 'PASSWORD_CHANGE' | 'PASSWORD_RESET'
  | 'DOCUMENT_UPLOAD' | 'DOCUMENT_DELETE' | 'DOCUMENT_DOWNLOAD'
  | 'ADMIN_ACCESS' | 'ADMIN_USER_CREATE' | 'ADMIN_USER_DELETE'
  | 'SECURITY_BREACH_ATTEMPT' | 'RATE_LIMIT_EXCEEDED'
  | 'CSRF_VIOLATION' | 'INVALID_SESSION'
  | 'AI_AGENT_QUERY' | 'AI_SUMMARY_GENERATION';

export type AuditOutcome = 'SUCCESS' | 'FAILURE' | 'ERROR';
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export interface AuditLogEntry {
  userId?: string;
  userEmail: string;
  action: AuditAction;
  resource?: string;
  details?: Record<string, any>;
  outcome: AuditOutcome;
  riskLevel?: RiskLevel;
  ipAddress?: string;
  userAgent?: string;
  sessionId?: string;
}

/**
 * LS-108: Comprehensive audit logging for security monitoring
 */
export class AuditLogger {
  /**
   * Log a security-relevant action
   */
  static async log(entry: AuditLogEntry): Promise<void> {
    try {
      const auditEntry = {
        id: undefined, // Will be generated by database
        userId: entry.userId || null,
        userEmail: entry.userEmail,
        action: entry.action,
        resource: entry.resource || null,
        details: entry.details || null,
        outcome: entry.outcome,
        riskLevel: entry.riskLevel || this.determineRiskLevel(entry.action, entry.outcome),
        ipAddress: entry.ipAddress || null,
        userAgent: entry.userAgent || null,
        sessionId: entry.sessionId || null,
        timestamp: new Date(),
      };

      await storage.createAuditLog(auditEntry);

      // Log critical events to console for immediate attention
      if (auditEntry.riskLevel === 'CRITICAL' || auditEntry.riskLevel === 'HIGH') {
        console.warn(`🚨 SECURITY ALERT: ${entry.action} by ${entry.userEmail} - ${entry.outcome}`, {
          details: entry.details,
          ip: entry.ipAddress,
          timestamp: new Date().toISOString()
        });
      }
    } catch (error) {
      console.error('Failed to write audit log:', error);
      // Don't throw error to avoid breaking the main operation
    }
  }

  /**
   * Log from Express request context
   */
  static async logFromRequest(
    req: Request, 
    action: AuditAction, 
    outcome: AuditOutcome,
    options: {
      resource?: string;
      details?: Record<string, any>;
      riskLevel?: RiskLevel;
    } = {}
  ): Promise<void> {
    const user = (req as any).user;
    const sessionId = (req.session as any)?.id || req.sessionID;
    
    await this.log({
      userId: user?.id || user?.claims?.sub,
      userEmail: user?.email || user?.claims?.email || 'anonymous',
      action,
      resource: options.resource,
      details: options.details,
      outcome,
      riskLevel: options.riskLevel,
      ipAddress: req.ip || req.connection.remoteAddress,
      userAgent: req.get('User-Agent'),
      sessionId,
    });
  }

  /**
   * Determine risk level based on action and outcome
   */
  private static determineRiskLevel(action: AuditAction, outcome: AuditOutcome): RiskLevel {
    // Critical risk actions
    if ([
      'ADMIN_USER_DELETE', 
      'SECURITY_BREACH_ATTEMPT',
      'CSRF_VIOLATION'
    ].includes(action)) {
      return 'CRITICAL';
    }

    // High risk actions
    if ([
      'ADMIN_ACCESS',
      'ADMIN_USER_CREATE',
      'PASSWORD_CHANGE',
      'INVALID_SESSION'
    ].includes(action)) {
      return 'HIGH';
    }

    // Medium risk for failed important actions
    if (outcome === 'FAILURE' && [
      'LOGIN',
      'DOCUMENT_DELETE',
      'PROFILE_UPDATE'
    ].includes(action)) {
      return 'MEDIUM';
    }

    // High risk for excessive failures
    if (action === 'RATE_LIMIT_EXCEEDED') {
      return 'HIGH';
    }

    return 'LOW';
  }

  /**
   * Convenience methods for common audit events
   */
  static async logLogin(req: Request, outcome: AuditOutcome, details?: Record<string, any>) {
    await this.logFromRequest(req, 'LOGIN', outcome, { details, riskLevel: outcome === 'FAILURE' ? 'MEDIUM' : 'LOW' });
  }

  static async logLogout(req: Request) {
    await this.logFromRequest(req, 'LOGOUT', 'SUCCESS', { riskLevel: 'LOW' });
  }

  static async logAdminAccess(req: Request, resource?: string) {
    await this.logFromRequest(req, 'ADMIN_ACCESS', 'SUCCESS', { 
      resource, 
      riskLevel: 'HIGH',
      details: { endpoint: req.path, method: req.method }
    });
  }

  static async logSecurityViolation(req: Request, violationType: string, details?: Record<string, any>) {
    await this.logFromRequest(req, 'SECURITY_BREACH_ATTEMPT', 'FAILURE', {
      riskLevel: 'CRITICAL',
      details: {
        violationType,
        ...details
      }
    });
  }

  static async logRateLimit(req: Request, details?: Record<string, any>) {
    await this.logFromRequest(req, 'RATE_LIMIT_EXCEEDED', 'FAILURE', {
      riskLevel: 'HIGH',
      details
    });
  }

  static async logDocumentAction(req: Request, action: 'DOCUMENT_UPLOAD' | 'DOCUMENT_DELETE' | 'DOCUMENT_DOWNLOAD', documentId: string, outcome: AuditOutcome = 'SUCCESS') {
    await this.logFromRequest(req, action, outcome, {
      resource: `document:${documentId}`,
      riskLevel: action === 'DOCUMENT_DELETE' ? 'MEDIUM' : 'LOW'
    });
  }
}

export default AuditLogger;