import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Diccionario de traducciones
const translations = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.features': 'Características',
    'nav.calculator': 'Calculadora',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.logout': 'Cerrar Sesión',
    'nav.profile': 'Mi Perfil',
    'nav.myFiles': 'Mis Archivos',
    'nav.contact': 'Contacto',
    'nav.adminPanel': 'Panel Admin',
    
    // Hero Section
    'hero.welcome': 'Bienvenido a',
    'hero.valueProposition': 'Descubre los secretos científicos de la longevidad. Herramientas personalizadas, recursos basados en evidencia y una comunidad dedicada a vivir más y mejor.',
    'hero.discoverMore': 'Descubre Más',
    
    // Features Section
    'features.title': '¿Por Qué Elegir',
    'features.subtitle': 'Nuestra plataforma combina ciencia de vanguardia con herramientas prácticas para ayudarte a vivir una vida más larga, saludable y plena.',
    'features.cognitiveHealth': 'Salud Cognitiva',
    'features.cognitiveDesc': 'Ejercicios y estrategias respaldadas por la ciencia para mantener tu mente aguda y prevenir el deterioro cognitivo.',
    'features.cardiovascularHealth': 'Salud Cardiovascular',
    'features.cardiovascularDesc': 'Protocolos personalizados para fortalecer tu corazón y sistema circulatorio, basados en tu perfil único.',
    'features.metabolicOptimization': 'Optimización Metabólica',
    'features.metabolicDesc': 'Herramientas para mejorar tu metabolismo, aumentar la energía y mantener un peso saludable.',
    'features.advancedPrevention': 'Prevención Avanzada',
    'features.preventionDesc': 'Estrategias proactivas de salud para prevenir enfermedades antes de que aparezcan.',
    'features.activeCommunity': 'Comunidad Activa',
    'features.communityDesc': 'Únete a miles de personas comprometidas con la longevidad y comparte tu viaje hacia una vida más plena.',
    'features.continuousResearch': 'Investigación Continua',
    'features.researchDesc': 'Acceso a los últimos descubrimientos en ciencia de la longevidad y medicina antienvejecimiento.',
    
    // Calculator Section
    'calculator.title': 'Calculadora',
    'calculator.subtitle': 'Descubre tu expectativa de vida basada en tu estilo de vida actual y obtén recomendaciones personalizadas para mejorarla.',
    'calculator.age': 'Edad',
    'calculator.gender': 'Sexo',
    'calculator.male': 'Masculino',
    'calculator.female': 'Femenino',
    'calculator.exercise': 'Frecuencia de Ejercicio',
    'calculator.exerciseDaily': 'Diariamente',
    'calculator.exerciseWeekly': '3-4 veces por semana',
    'calculator.exerciseOccasional': 'Ocasionalmente',
    'calculator.exerciseNever': 'Nunca',
    'calculator.smoking': 'Hábito de Fumar',
    'calculator.smokingNever': 'Nunca he fumado',
    'calculator.smokingFormer': 'Ex fumador',
    'calculator.smokingCurrent': 'Fumador actual',
    'calculator.diet': 'Tipo de Dieta',
    'calculator.dietMediterranean': 'Mediterránea',
    'calculator.dietBalanced': 'Balanceada',
    'calculator.dietProcessed': 'Alta en procesados',
    'calculator.calculate': 'Calcular Expectativa',
    'calculator.result': 'Tu expectativa de vida estimada es de',
    'calculator.years': 'años',
    'calculator.joinUs': 'Únete para Mejorar',
    'calculator.agePlaceholder': 'Ej: 35',
    'calculator.genderOther': 'Otro',
    'calculator.formTitle': 'Calculadora de Longevidad',
    'calculator.dietPlaceholder': '¿Cómo describes tu dieta?',
    'calculator.dietWestern': 'Occidental típica',
    'calculator.dietPoor': 'Poco saludable',
    'calculator.buttonText': 'Calcular mi Longevidad',
    'calculator.resultsTitle': 'Tus Resultados',
    'calculator.lifeExpectancy': 'Expectativa de vida estimada',
    'calculator.cardiovascularHealth': 'Salud Cardiovascular',
    'calculator.activityLevel': 'Nivel de Actividad',
    'calculator.mainRecommendations': 'Recomendaciones Principales:',
    'calculator.recommendation1': 'Incrementa tu actividad física a 150 min/semana',
    'calculator.recommendation2': 'Adopta una dieta rica en antioxidantes',
    'calculator.recommendation3': 'Mejora la calidad de tu sueño',
    'calculator.recommendation4': 'Practica técnicas de manejo del estrés',
    'calculator.getPersonalizedPlan': 'Obtener Plan Personalizado',
    'calculator.contactSpecialist': 'Contactar Especialista',
    'calculator.emptyStateMessage': 'Completa el formulario para conocer tu expectativa de vida y recibir recomendaciones personalizadas.',
    'calculator.configuringStatus': 'Configurando calculadora con datos de {company}...',
    'calculator.defaultAlgorithmStatus': 'Calculadora usando algoritmos predeterminados',
    'calculator.personalizedStatus': 'Contenido personalizado para {company}',
    
    // Notifications
    'notifications.success.loginTitle': '¡Bienvenido!',
    'notifications.success.loginDesc': 'Has iniciado sesión exitosamente.',
    'notifications.success.logoutTitle': 'Sesión cerrada',
    'notifications.success.logoutDesc': 'Has cerrado sesión de forma segura.',
    'notifications.success.profileTitle': 'Perfil actualizado',
    'notifications.success.profileDesc': 'Tu información personal se ha guardado correctamente.',
    'notifications.success.documentTitle': 'Documento subido',
    'notifications.success.documentDesc': '{fileName} se ha subido exitosamente.',
    'notifications.success.deleteTitle': 'Documento eliminado',
    'notifications.success.deleteDesc': 'El documento ha sido eliminado correctamente.',
    'notifications.success.emailTitle': 'Email verificado',
    'notifications.success.emailDesc': 'Tu dirección de email ha sido confirmada.',
    'notifications.success.passwordTitle': 'Contraseña restablecida',
    'notifications.success.passwordDesc': 'Tu contraseña ha sido actualizada exitosamente.',
    'notifications.error.loginTitle': 'Error de inicio de sesión',
    'notifications.error.loginDesc': 'Credenciales incorrectas. Intenta nuevamente.',
    'notifications.error.uploadTitle': 'Error al subir archivo',
    'notifications.error.uploadDesc': 'No se pudo subir el archivo. Intenta nuevamente.',
    'notifications.error.uploadFileDesc': 'No se pudo subir {fileName}. Verifica el formato y tamaño.',
    'notifications.error.profileTitle': 'Error al actualizar perfil',
    'notifications.error.profileDesc': 'No se pudieron guardar los cambios. Intenta nuevamente.',
    'notifications.error.networkTitle': 'Error de conexión',
    'notifications.error.networkDesc': 'Verifica tu conexión a internet e intenta nuevamente.',
    'notifications.error.unauthorizedTitle': 'Sesión expirada',
    'notifications.error.unauthorizedDesc': 'Tu sesión ha expirado. Inicia sesión nuevamente.',
    'notifications.error.validationTitle': 'Error de validación',
    'notifications.error.validationDesc': 'Por favor verifica el campo: {field}',
    'notifications.info.sessionTitle': 'Sesión por expirar',
    'notifications.info.sessionDesc': 'Tu sesión expirará en {minutes} minutos.',
    'notifications.info.processingTitle': 'Procesando documento',
    'notifications.info.processingDesc': 'Tu documento está siendo analizado. Te notificaremos cuando esté listo.',
    'notifications.info.comingSoonTitle': 'Próximamente',
    'notifications.info.comingSoonDesc': 'La función {feature} estará disponible pronto.',
    'notifications.info.autoSaveTitle': 'Guardado automático',
    'notifications.info.autoSaveDesc': 'Tus cambios han sido guardados automáticamente.',
    'notifications.warning.timeoutTitle': 'Advertencia de sesión',
    'notifications.warning.timeoutDesc': 'Tu sesión está por expirar. Guarda tu trabajo.',
    'notifications.warning.unsavedTitle': 'Cambios sin guardar',
    'notifications.warning.unsavedDesc': 'Tienes cambios sin guardar. ¿Deseas continuar?',
    'notifications.warning.storageTitle': 'Límite de almacenamiento',
    'notifications.warning.storageDesc': 'Estás cerca del límite de almacenamiento. Considera eliminar archivos antiguos.',
    'notifications.warning.docLimitTitle': 'Límite de documentos',
    'notifications.warning.docLimitDesc': 'Has alcanzado el límite de documentos. Elimina algunos para subir más.',
    
    // Login Page
    'login.title': 'Iniciar Sesión',
    'login.subtitle': 'Ingresa a tu cuenta de Evity',
    'login.email': 'Email',
    'login.password': 'Contraseña',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.loginButton': 'Iniciar Sesión',
    'login.loggingIn': 'Iniciando sesión...',
    'login.noAccount': '¿No tienes cuenta?',
    'login.signUpHere': 'Regístrate aquí',
    'login.back': 'Volver',
    'login.invalidEmail': 'Ingresa un email válido',
    'login.emailRequired': 'El email es requerido',
    'login.passwordRequired': 'La contraseña es requerida',
    
    // Register Page
    'register.title': 'Crear Cuenta',
    'register.subtitle': 'Completa tus datos para crear tu cuenta en Evity',
    'register.firstName': 'Nombre',
    'register.lastName': 'Apellido',
    'register.email': 'Email',
    'register.password': 'Contraseña',
    'register.confirmPassword': 'Confirmar Contraseña',
    'register.gender': 'Sexo',
    'register.genderMale': 'Masculino',
    'register.genderFemale': 'Femenino',
    'register.genderOther': 'Otro',
    'register.phoneNumber': 'Teléfono',
    'register.registerButton': 'Crear Cuenta',
    'register.registering': 'Creando cuenta...',
    'register.haveAccount': '¿Ya tienes cuenta?',
    'register.loginHere': 'Inicia sesión aquí',
    'register.firstNameMin': 'El nombre debe tener al menos 2 caracteres',
    'register.firstNameMax': 'El nombre no puede exceder 50 caracteres',
    'register.firstNameInvalid': 'El nombre solo puede contener letras y espacios',
    'register.lastNameMin': 'El apellido debe tener al menos 2 caracteres',
    'register.lastNameMax': 'El apellido no puede exceder 50 caracteres',
    'register.lastNameInvalid': 'El apellido solo puede contener letras y espacios',
    'register.invalidEmail': 'Ingresa un email válido',
    'register.emailRequired': 'El email es requerido',
    'register.emailMax': 'El email no puede exceder 100 caracteres',
    'register.passwordMin': 'La contraseña debe tener al menos 8 caracteres',
    'register.passwordMax': 'La contraseña no puede exceder 100 caracteres',
    'register.passwordInvalid': 'La contraseña debe contener al menos una minúscula, una mayúscula y un número',
    'register.confirmRequired': 'Confirma tu contraseña',
    'register.genderInvalid': 'Selecciona una opción válida',
    'register.passwordMismatch': 'Las contraseñas no coinciden',
    'register.backButton': 'Volver',
    'register.description': 'Completa tus datos para empezar tu viaje hacia una vida más saludable',
    'register.firstNameLabel': 'Nombre *',
    'register.lastNameLabel': 'Apellido *',
    'register.emailLabel': 'Email *',
    'register.passwordLabel': 'Contraseña *',
    'register.confirmPasswordLabel': 'Confirmar Contraseña *',
    'register.genderLabel': 'Género',
    'register.phoneLabel': 'Teléfono *',
    'register.successToast': '¡Registro exitoso!',
    'register.successToastDesc': 'Tu cuenta ha sido creada correctamente. Bienvenido a Evity.',
    'register.errorToast': 'Error de registro',
    'register.errorDuringToast': 'Error durante el registro',
    'register.firstNamePlaceholder': 'Tu nombre',
    'register.lastNamePlaceholder': 'Tu apellido',
    'register.emailPlaceholder': 'tu@email.com',
    'register.passwordPlaceholder': 'Crea una contraseña segura',
    'register.confirmPasswordPlaceholder': 'Confirma tu contraseña',
    'register.phonePlaceholder': 'Ej: +52 5551234567 (MX) o +1 5551234567 (US)',
    'register.genderPlaceholder': 'Selecciona una opción',
    
    // Footer
    'footer.company': 'Empresa',
    'footer.aboutUs': 'Sobre Nosotros',
    'footer.research': 'Investigación',
    'footer.team': 'Equipo',
    'footer.services': 'Servicios',
    'footer.healthAssessment': 'Evaluación de Salud',
    'footer.personalizedPlans': 'Planes Personalizados',
    'footer.community': 'Comunidad',
    'footer.resources': 'Recursos',
    'footer.blog': 'Blog',
    'footer.guides': 'Guías',
    'footer.calculator': 'Calculadora',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacidad',
    'footer.companyDescription': 'Tu plataforma de longevidad personalizada. Basado en ciencia, diseñado para ti.',
    'footer.madeWithLove': 'Hecho con amor para tu bienestar',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.faq': 'Preguntas Frecuentes',
    'footer.calculators': 'Calculadoras',
    'footer.location': 'Madrid, España',
    'footer.allRightsReserved': 'Todos los derechos reservados',
    'footer.privacyPolicy': 'Política de Privacidad',
    'footer.termsOfUse': 'Términos de Uso',
    'footer.cookies': 'Cookies',
    'footer.terms': 'Términos',
    
    // About Page
    'about.pageTitle': 'Acerca de Nosotros',
    'about.meetCompany': 'Conoce a',
    'about.mission': 'Nuestra Misión',
    'about.vision': 'Nuestra Visión',
    'about.team': 'Nuestro Equipo',
    'about.teamSubtitle': 'Conoce a los expertos que están revolucionando el futuro de la longevidad y el bienestar',
    'about.contact': 'Contactar',
    'about.contactUs': 'Contáctanos',
    'about.loadingInfo': 'Cargando información de la empresa...',
    'about.errorLoading': 'Error al cargar información',
    'about.errorDescription': 'No se pudo cargar la información de la empresa. Por favor, inténtalo más tarde.',
    'about.noInfo': 'No hay información disponible.',
    'about.ctaTitle': '¿Listo para transformar tu longevidad?',
    'about.ctaDescription': 'Únete a nuestra comunidad y comienza tu viaje hacia una vida más larga y saludable',
    'about.registerNow': 'Registrarse Ahora',
    
    // My Files Page
    'files.title': 'Mis Archivos Médicos',
    'files.subtitle': 'Gestiona tus estudios y resultados de laboratorio',
    'files.search': 'Buscar archivos...',
    'files.fileName': 'Nombre del Archivo',
    'files.type': 'Tipo',
    'files.size': 'Tamaño',
    'files.uploadDate': 'Fecha de Subida',
    'files.actions': 'Acciones',
    'files.preview': 'Vista Previa',
    'files.download': 'Descargar',
    'files.delete': 'Eliminar',
    'files.study': 'Estudio',
    'files.lab': 'Laboratorio',
    'files.noFiles': 'No se encontraron archivos',
    'files.upload': 'Subir Archivo',
    'files.deleteSuccess': 'Archivo eliminado',
    'files.deleteSuccessDescription': 'El archivo se eliminó correctamente',
    'files.deleteErrorDefault': 'No se pudo eliminar el archivo',
    'files.previewError': 'No se pudo previsualizar el archivo',
    'files.downloadStarted': 'Descarga iniciada',
    'files.downloading': 'Se está descargando',
    'files.downloadError': 'No se pudo descargar el archivo',
    'files.loadError': 'Error al cargar archivos',
    'files.loadErrorDescription': 'No se pudieron cargar tus archivos médicos.',
    'files.searchPlaceholder': 'Buscar por nombre de archivo...',
    'files.showingResultsFor': 'Mostrando resultados para',
    'files.medicalFiles': 'Archivos Médicos',
    'files.fileType': 'Tipo',
    'files.perPageLabel': 'por página',
    'files.noFilesTitle': 'No tienes archivos',
    'files.noFilesSearch': 'No se encontraron archivos que coincidan con tu búsqueda.',
    'files.noFilesEmpty': 'Aún no has subido ningún archivo médico.',
    'files.other': 'OTRO',
    'files.totalSingular': 'total',
    'files.totalPlural': 'totales',
    'files.showing': 'de',
    'files.filesSingular': 'archivo',
    'files.filesPlural': 'archivos',
    'files.pageOf': 'Página {current} de {total}',
    
    // Landing Page
    'landing.cardiovascularHealth': 'Salud Cardiovascular',
    'landing.cardiovascularDesc': 'Análisis completo de tu sistema cardiovascular con las últimas tecnologías',
    'landing.cognitiveFunction': 'Función Cognitiva',
    'landing.cognitiveDesc': 'Evaluación de memoria, concentración y rendimiento cerebral',
    'landing.personalizedGenetics': 'Genética Personalizada', 
    'landing.geneticsDesc': 'Análisis genético para una medicina verdaderamente personalizada',
    'landing.advancedPrevention': 'Prevención Avanzada',
    'landing.preventionDesc': 'Detecta riesgos antes de que se conviertan en problemas',
    'landing.specializedLabs': 'Laboratorios Especializados',
    'landing.labsDesc': 'Estudios de laboratorio de vanguardia para longevidad',
    'landing.continuousMonitoring': 'Monitoreo Continuo',
    'landing.monitoringDesc': 'Seguimiento personalizado de tu progreso hacia una vida más larga',
    'landing.heroMission': 'Transformar la forma en que las personas envejecen, proporcionando herramientas científicas y personalizadas para vivir vidas más largas, saludables y plenas.',
    'landing.accessProfile': 'Acceder a mi Perfil',
    'landing.createAccount': 'Crear Cuenta',
    'landing.heroCaption': 'Inicia sesión o crea una cuenta para cargar tus estudios y laboratorios',
    'landing.whyChoose': '¿Por qué elegir Evity?',
    'landing.ourVision': 'Nuestra Visión',
    'landing.visionFallback': 'Ayudarte a vivir más y a vivir mejor',
    'landing.startJourney': 'Comienza tu Viaje hacia la Longevidad',
    'landing.ctaDescription': 'Accede a tu perfil personal y carga tus estudios médicos para recibir análisis personalizados',
    'landing.signIn': 'Iniciar Sesión',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.close': 'Cerrar',
    'common.confirm': 'Confirmar',
    'common.or': 'o',
    'common.and': 'y',
    'common.required': 'requerido',
    'common.optional': 'opcional',
    'common.saving': 'Guardando...',
    'common.retry': 'Reintentar',
    'common.search': 'Buscar',
    'common.clear': 'Limpiar',
    'common.download': 'Descargar',
    
    // File Upload
    'fileUpload.medicalStudies': 'estudios médicos',
    'fileUpload.labResults': 'resultados de laboratorio',
    'fileUpload.dragHere': 'Arrastra archivos aquí o haz clic para seleccionar',
    'fileUpload.formats': 'PDF, imágenes, Word • Máximo 10MB',
    'fileUpload.upload': 'Subir',
    'fileUpload.uploading': 'Subiendo...',
    'fileUpload.fileTooLarge': 'El archivo es demasiado grande. Máximo 10MB.',
    'fileUpload.invalidFileType': 'Tipo de archivo no permitido. Solo PDF, imágenes y documentos de Word.',
    'fileUpload.uploadError': 'Error al subir archivo',
    'fileUpload.unknownError': 'Error desconocido',
    'fileUpload.fileSizeValidation': 'tamaño de archivo (máximo 10MB, recibido {size}MB)',
    'fileUpload.fileTypeValidation': 'tipo de archivo (solo PDF, imágenes y documentos de Word)',
    
    // Profile Page
    'profile.loadingProfile': 'Cargando perfil...',
    'profile.backHome': 'Inicio',
    'profile.myProfile': 'Mi Perfil',
    'profile.logout': 'Cerrar Sesión',
    'profile.personalInfo': 'Información Personal',
    'profile.edit': 'Editar',
    'profile.editTitle': 'Editar Información Personal',
    'profile.editDescription': 'Actualiza tu información personal. Los cambios se guardarán inmediatamente.',
    'profile.firstName': 'Nombre',
    'profile.firstNamePlaceholder': 'Tu nombre',
    'profile.lastName': 'Apellido',
    'profile.lastNamePlaceholder': 'Tu apellido',
    'profile.email': 'Email',
    'profile.emailPlaceholder': 'tu@email.com',
    'profile.phone': 'Teléfono',
    'profile.phonePlaceholder': 'Número de teléfono',
    'profile.gender': 'Género',
    'profile.genderPlaceholder': 'Selecciona tu género',
    'profile.genderMale': 'Masculino',
    'profile.genderFemale': 'Femenino',
    'profile.genderOther': 'Otro',
    'profile.genderPreferNotToSay': 'Prefiero no decir',
    'profile.saveChanges': 'Guardar Cambios',
    'profile.cancel': 'Cancelar',
    'profile.accountType': 'Tipo de Cuenta',
    'profile.verified': 'Verificada',
    'profile.joinDate': 'Fecha de Registro',
    'profile.medicalDocuments': 'Mis Documentos Médicos',
    'profile.documentsDescription': 'Gestiona y visualiza tus estudios médicos y resultados de laboratorio',
    'profile.searchDocuments': 'Buscar documentos...',
    'profile.allTypes': 'Todos los tipos',
    'profile.studies': 'Estudios',
    'profile.labResults': 'Laboratorios',
    'profile.noDocuments': 'No tienes documentos cargados aún',
    'profile.noDocumentsDescription': 'Comienza subiendo tus estudios médicos y resultados de laboratorio para obtener análisis personalizados.',
    'profile.uploadFirst': 'Subir mi primer documento',
    'profile.noMatchingDocuments': 'No se encontraron documentos',
    'profile.noMatchingDescription': 'No hay documentos que coincidan con los criterios de búsqueda.',
    'profile.clearSearch': 'Limpiar búsqueda',
    'profile.fileName': 'Nombre del archivo',
    'profile.uploadDate': 'Fecha de carga',
    'profile.fileSize': 'Tamaño',
    'profile.actions': 'Acciones',
    'profile.preview': 'Vista previa',
    'profile.download': 'Descargar',
    'profile.delete': 'Eliminar',
    'profile.confirmDelete': '¿Eliminar documento?',
    'profile.confirmDeleteDescription': 'Esta acción no se puede deshacer. El documento será eliminado permanentemente.',
  },
  
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.features': 'Features',
    'nav.calculator': 'Calculator',
    'nav.login': 'Login',
    'nav.register': 'Sign Up',
    'nav.logout': 'Logout',
    'nav.profile': 'My Profile',
    'nav.myFiles': 'My Files',
    'nav.contact': 'Contact',
    'nav.adminPanel': 'Admin Panel',
    
    // Hero Section
    'hero.welcome': 'Welcome to',
    'hero.valueProposition': 'Discover the scientific secrets of longevity. Personalized tools, evidence-based resources and a community dedicated to living longer and better.',
    'hero.discoverMore': 'Discover More',
    
    // Features Section
    'features.title': 'Why Choose',
    'features.subtitle': 'Our platform combines cutting-edge science with practical tools to help you live a longer, healthier and more fulfilling life.',
    'features.cognitiveHealth': 'Cognitive Health',
    'features.cognitiveDesc': 'Science-backed exercises and strategies to keep your mind sharp and prevent cognitive decline.',
    'features.cardiovascularHealth': 'Cardiovascular Health',
    'features.cardiovascularDesc': 'Personalized protocols to strengthen your heart and circulatory system, based on your unique profile.',
    'features.metabolicOptimization': 'Metabolic Optimization',
    'features.metabolicDesc': 'Tools to improve your metabolism, increase energy and maintain a healthy weight.',
    'features.advancedPrevention': 'Advanced Prevention',
    'features.preventionDesc': 'Proactive health strategies to prevent diseases before they appear.',
    'features.activeCommunity': 'Active Community',
    'features.communityDesc': 'Join thousands of people committed to longevity and share your journey to a fuller life.',
    'features.continuousResearch': 'Continuous Research',
    'features.researchDesc': 'Access to the latest discoveries in longevity science and anti-aging medicine.',
    
    // Calculator Section
    'calculator.title': 'Calculator',
    'calculator.subtitle': 'Discover your life expectancy based on your current lifestyle and get personalized recommendations to improve it.',
    'calculator.age': 'Age',
    'calculator.gender': 'Gender',
    'calculator.male': 'Male',
    'calculator.female': 'Female',
    'calculator.exercise': 'Exercise Frequency',
    'calculator.exerciseDaily': 'Daily',
    'calculator.exerciseWeekly': '3-4 times per week',
    'calculator.exerciseOccasional': 'Occasionally',
    'calculator.exerciseNever': 'Never',
    'calculator.smoking': 'Smoking Habit',
    'calculator.smokingNever': 'Never smoked',
    'calculator.smokingFormer': 'Former smoker',
    'calculator.smokingCurrent': 'Current smoker',
    'calculator.diet': 'Diet Type',
    'calculator.dietMediterranean': 'Mediterranean',
    'calculator.dietBalanced': 'Balanced',
    'calculator.dietProcessed': 'High in processed foods',
    'calculator.calculate': 'Calculate Expectancy',
    'calculator.result': 'Your estimated life expectancy is',
    'calculator.years': 'years',
    'calculator.joinUs': 'Join Us to Improve',
    'calculator.agePlaceholder': 'Ex: 35',
    'calculator.genderOther': 'Other',
    'calculator.formTitle': 'Longevity Calculator',
    'calculator.dietPlaceholder': 'How would you describe your diet?',
    'calculator.dietWestern': 'Typical Western',
    'calculator.dietPoor': 'Unhealthy',
    'calculator.buttonText': 'Calculate My Longevity',
    'calculator.resultsTitle': 'Your Results',
    'calculator.lifeExpectancy': 'Estimated life expectancy',
    'calculator.cardiovascularHealth': 'Cardiovascular Health',
    'calculator.activityLevel': 'Activity Level',
    'calculator.mainRecommendations': 'Main Recommendations:',
    'calculator.recommendation1': 'Increase your physical activity to 150 min/week',
    'calculator.recommendation2': 'Adopt an antioxidant-rich diet',
    'calculator.recommendation3': 'Improve your sleep quality',
    'calculator.recommendation4': 'Practice stress management techniques',
    'calculator.getPersonalizedPlan': 'Get Personalized Plan',
    'calculator.contactSpecialist': 'Contact Specialist',
    'calculator.emptyStateMessage': 'Complete the form to know your life expectancy and receive personalized recommendations.',
    'calculator.configuringStatus': 'Setting up calculator with {company} data...',
    'calculator.defaultAlgorithmStatus': 'Calculator using default algorithms',
    'calculator.personalizedStatus': 'Personalized content for {company}',
    
    // Notifications
    'notifications.success.loginTitle': 'Welcome!',
    'notifications.success.loginDesc': 'You have successfully signed in.',
    'notifications.success.logoutTitle': 'Session closed',
    'notifications.success.logoutDesc': 'You have safely signed out.',
    'notifications.success.profileTitle': 'Profile updated',
    'notifications.success.profileDesc': 'Your personal information has been saved successfully.',
    'notifications.success.documentTitle': 'Document uploaded',
    'notifications.success.documentDesc': '{fileName} has been uploaded successfully.',
    'notifications.success.deleteTitle': 'Document deleted',
    'notifications.success.deleteDesc': 'The document has been deleted successfully.',
    'notifications.success.emailTitle': 'Email verified',
    'notifications.success.emailDesc': 'Your email address has been confirmed.',
    'notifications.success.passwordTitle': 'Password reset',
    'notifications.success.passwordDesc': 'Your password has been updated successfully.',
    'notifications.error.loginTitle': 'Login error',
    'notifications.error.loginDesc': 'Invalid credentials. Please try again.',
    'notifications.error.uploadTitle': 'File upload error',
    'notifications.error.uploadDesc': 'Could not upload the file. Please try again.',
    'notifications.error.uploadFileDesc': 'Could not upload {fileName}. Check the format and size.',
    'notifications.error.profileTitle': 'Profile update error',
    'notifications.error.profileDesc': 'Could not save changes. Please try again.',
    'notifications.error.networkTitle': 'Connection error',
    'notifications.error.networkDesc': 'Check your internet connection and try again.',
    'notifications.error.unauthorizedTitle': 'Session expired',
    'notifications.error.unauthorizedDesc': 'Your session has expired. Please sign in again.',
    'notifications.error.validationTitle': 'Validation error',
    'notifications.error.validationDesc': 'Please check the field: {field}',
    'notifications.info.sessionTitle': 'Session expiring',
    'notifications.info.sessionDesc': 'Your session will expire in {minutes} minutes.',
    'notifications.info.processingTitle': 'Processing document',
    'notifications.info.processingDesc': 'Your document is being analyzed. We will notify you when it is ready.',
    'notifications.info.comingSoonTitle': 'Coming soon',
    'notifications.info.comingSoonDesc': 'The {feature} feature will be available soon.',
    'notifications.info.autoSaveTitle': 'Auto saved',
    'notifications.info.autoSaveDesc': 'Your changes have been saved automatically.',
    'notifications.warning.timeoutTitle': 'Session warning',
    'notifications.warning.timeoutDesc': 'Your session is about to expire. Save your work.',
    'notifications.warning.unsavedTitle': 'Unsaved changes',
    'notifications.warning.unsavedDesc': 'You have unsaved changes. Do you want to continue?',
    'notifications.warning.storageTitle': 'Storage limit',
    'notifications.warning.storageDesc': 'You are approaching your storage limit. Consider deleting old files.',
    'notifications.warning.docLimitTitle': 'Document limit',
    'notifications.warning.docLimitDesc': 'You have reached the document limit. Delete some to upload more.',
    
    // Login Page
    'login.title': 'Login',
    'login.subtitle': 'Sign in to your Evity account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot your password?',
    'login.loginButton': 'Login',
    'login.loggingIn': 'Logging in...',
    'login.noAccount': "Don't have an account?",
    'login.signUpHere': 'Sign up here',
    'login.back': 'Back',
    'login.invalidEmail': 'Please enter a valid email',
    'login.emailRequired': 'Email is required',
    'login.passwordRequired': 'Password is required',
    
    // Register Page
    'register.title': 'Create Account',
    'register.subtitle': 'Complete your details to create your Evity account',
    'register.firstName': 'First Name',
    'register.lastName': 'Last Name',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm Password',
    'register.gender': 'Gender',
    'register.genderMale': 'Male',
    'register.genderFemale': 'Female',
    'register.genderOther': 'Other',
    'register.phoneNumber': 'Phone',
    'register.registerButton': 'Create Account',
    'register.registering': 'Creating account...',
    'register.haveAccount': 'Already have an account?',
    'register.loginHere': 'Sign in here',
    'register.firstNameMin': 'First name must be at least 2 characters',
    'register.firstNameMax': 'First name cannot exceed 50 characters',
    'register.firstNameInvalid': 'First name can only contain letters and spaces',
    'register.lastNameMin': 'Last name must be at least 2 characters',
    'register.lastNameMax': 'Last name cannot exceed 50 characters',
    'register.lastNameInvalid': 'Last name can only contain letters and spaces',
    'register.invalidEmail': 'Please enter a valid email',
    'register.emailRequired': 'Email is required',
    'register.emailMax': 'Email cannot exceed 100 characters',
    'register.passwordMin': 'Password must be at least 8 characters',
    'register.passwordMax': 'Password cannot exceed 100 characters',
    'register.passwordInvalid': 'Password must contain at least one lowercase, one uppercase and one number',
    'register.confirmRequired': 'Please confirm your password',
    'register.genderInvalid': 'Please select a valid option',
    'register.passwordMismatch': 'Passwords do not match',
    'register.backButton': 'Back',
    'register.description': 'Complete your information to start your journey toward a healthier life',
    'register.firstNameLabel': 'First Name *',
    'register.lastNameLabel': 'Last Name *',
    'register.emailLabel': 'Email *',
    'register.passwordLabel': 'Password *',
    'register.confirmPasswordLabel': 'Confirm Password *',
    'register.genderLabel': 'Gender',
    'register.phoneLabel': 'Phone *',
    'register.successToast': 'Registration successful!',
    'register.successToastDesc': 'Your account has been created successfully. Welcome to Evity.',
    'register.errorToast': 'Registration error',
    'register.errorDuringToast': 'Error during registration',
    'register.firstNamePlaceholder': 'Your first name',
    'register.lastNamePlaceholder': 'Your last name',
    'register.emailPlaceholder': 'your@email.com',
    'register.passwordPlaceholder': 'Create a secure password',
    'register.confirmPasswordPlaceholder': 'Confirm your password',
    'register.phonePlaceholder': 'Ex: +52 5551234567 (MX) or +1 5551234567 (US)',
    'register.genderPlaceholder': 'Select an option',
    
    // Footer
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.research': 'Research',
    'footer.team': 'Team',
    'footer.services': 'Services',
    'footer.healthAssessment': 'Health Assessment',
    'footer.personalizedPlans': 'Personalized Plans',
    'footer.community': 'Community',
    'footer.resources': 'Resources',
    'footer.blog': 'Blog',
    'footer.guides': 'Guides',
    'footer.calculator': 'Calculator',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.cookies': 'Cookies',
    'footer.madeWithLove': 'Made with love for your wellbeing',
    'footer.allRightsReserved': 'All rights reserved.',
    'footer.companyDescription': 'Your personalized longevity platform. Science-based, designed for you.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.faq': 'FAQ',
    'footer.calculators': 'Calculators',
    'footer.location': 'Madrid, Spain',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfUse': 'Terms of Use',
    
    // About Page
    'about.pageTitle': 'About Us',
    'about.meetCompany': 'Meet',
    'about.mission': 'Our Mission',
    'about.vision': 'Our Vision',
    'about.team': 'Our Team',
    'about.teamSubtitle': 'Meet the experts who are revolutionizing the future of longevity and wellness',
    'about.contact': 'Contact',
    'about.contactUs': 'Contact Us',
    'about.loadingInfo': 'Loading company information...',
    'about.errorLoading': 'Error loading information',
    'about.errorDescription': 'Could not load company information. Please try again later.',
    'about.noInfo': 'No information available.',
    'about.ctaTitle': 'Ready to transform your longevity?',
    'about.ctaDescription': 'Join our community and start your journey towards a longer, healthier life',
    'about.registerNow': 'Register Now',
    
    // My Files Page
    'files.title': 'My Medical Files',
    'files.subtitle': 'Manage your studies and lab results',
    'files.search': 'Search files...',
    'files.fileName': 'File Name',
    'files.type': 'Type',
    'files.size': 'Size',
    'files.uploadDate': 'Upload Date',
    'files.actions': 'Actions',
    'files.preview': 'Preview',
    'files.download': 'Download',
    'files.delete': 'Delete',
    'files.study': 'Study',
    'files.lab': 'Lab',
    'files.noFiles': 'No files found',
    'files.upload': 'Upload File',
    'files.deleteSuccess': 'File deleted',
    'files.deleteSuccessDescription': 'The file was deleted successfully',
    'files.deleteErrorDefault': 'Could not delete the file',
    'files.previewError': 'Could not preview the file',
    'files.downloadStarted': 'Download started',
    'files.downloading': 'Downloading',
    'files.downloadError': 'Could not download the file',
    'files.loadError': 'Error loading files',
    'files.loadErrorDescription': 'Could not load your medical files.',
    'files.searchPlaceholder': 'Search by file name...',
    'files.showingResultsFor': 'Showing results for',
    'files.medicalFiles': 'Medical Files',
    'files.fileType': 'Type',
    'files.perPageLabel': 'per page',
    'files.noFilesTitle': 'No files yet',
    'files.noFilesSearch': 'No files found matching your search.',
    'files.noFilesEmpty': 'You haven\'t uploaded any medical files yet.',
    'files.other': 'OTHER',
    'files.totalSingular': 'total',
    'files.totalPlural': 'total',
    'files.showing': 'of',
    'files.filesSingular': 'file',
    'files.filesPlural': 'files',
    'files.pageOf': 'Page {current} of {total}',
    
    // Landing Page
    'landing.cardiovascularHealth': 'Cardiovascular Health',
    'landing.cardiovascularDesc': 'Complete analysis of your cardiovascular system with the latest technologies',
    'landing.cognitiveFunction': 'Cognitive Function',
    'landing.cognitiveDesc': 'Evaluation of memory, concentration and brain performance',
    'landing.personalizedGenetics': 'Personalized Genetics', 
    'landing.geneticsDesc': 'Genetic analysis for truly personalized medicine',
    'landing.advancedPrevention': 'Advanced Prevention',
    'landing.preventionDesc': 'Detect risks before they become problems',
    'landing.specializedLabs': 'Specialized Laboratories',
    'landing.labsDesc': 'Cutting-edge laboratory studies for longevity',
    'landing.continuousMonitoring': 'Continuous Monitoring',
    'landing.monitoringDesc': 'Personalized tracking of your progress towards a longer life',
    'landing.heroMission': 'Transform the way people age, providing scientific and personalized tools to live longer, healthier and more fulfilling lives.',
    'landing.accessProfile': 'Access My Profile',
    'landing.createAccount': 'Create Account',
    'landing.heroCaption': 'Sign in or create an account to upload your studies and laboratory results',
    'landing.whyChoose': 'Why choose Evity?',
    'landing.ourVision': 'Our Vision',
    'landing.visionFallback': 'Help you live longer and live better',
    'landing.startJourney': 'Start Your Journey to Longevity',
    'landing.ctaDescription': 'Access your personal profile and upload your medical studies to receive personalized analysis',
    'landing.signIn': 'Sign In',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.or': 'or',
    'common.and': 'and',
    'common.required': 'required',
    'common.optional': 'optional',
    'common.saving': 'Saving...',
    'common.retry': 'Retry',
    'common.search': 'Search',
    'common.clear': 'Clear',
    'common.download': 'Download',
    
    // File Upload
    'fileUpload.medicalStudies': 'medical studies',
    'fileUpload.labResults': 'lab results',
    'fileUpload.dragHere': 'Drag files here or click to select',
    'fileUpload.formats': 'PDF, images, Word • Maximum 10MB',
    'fileUpload.upload': 'Upload',
    'fileUpload.uploading': 'Uploading...',
    'fileUpload.fileTooLarge': 'File is too large. Maximum 10MB.',
    'fileUpload.invalidFileType': 'File type not allowed. Only PDF, images and Word documents.',
    'fileUpload.uploadError': 'Upload error',
    'fileUpload.unknownError': 'Unknown error',
    'fileUpload.fileSizeValidation': 'file size (maximum 10MB, received {size}MB)',
    'fileUpload.fileTypeValidation': 'file type (only PDF, images and Word documents)',
    
    // Profile Page
    'profile.loadingProfile': 'Loading profile...',
    'profile.backHome': 'Home',
    'profile.myProfile': 'My Profile',
    'profile.logout': 'Logout',
    'profile.personalInfo': 'Personal Information',
    'profile.edit': 'Edit',
    'profile.editTitle': 'Edit Personal Information',
    'profile.editDescription': 'Update your personal information. Changes will be saved immediately.',
    'profile.firstName': 'First Name',
    'profile.firstNamePlaceholder': 'Your first name',
    'profile.lastName': 'Last Name',
    'profile.lastNamePlaceholder': 'Your last name',
    'profile.email': 'Email',
    'profile.emailPlaceholder': 'you@email.com',
    'profile.phone': 'Phone',
    'profile.phonePlaceholder': 'Phone number',
    'profile.gender': 'Gender',
    'profile.genderPlaceholder': 'Select your gender',
    'profile.genderMale': 'Male',
    'profile.genderFemale': 'Female',
    'profile.genderOther': 'Other',
    'profile.genderPreferNotToSay': 'Prefer not to say',
    'profile.saveChanges': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.accountType': 'Account Type',
    'profile.verified': 'Verified',
    'profile.joinDate': 'Join Date',
    'profile.medicalDocuments': 'My Medical Documents',
    'profile.documentsDescription': 'Manage and view your medical studies and lab results',
    'profile.searchDocuments': 'Search documents...',
    'profile.allTypes': 'All types',
    'profile.studies': 'Studies',
    'profile.labResults': 'Lab Results',
    'profile.noDocuments': 'You have no documents uploaded yet',
    'profile.noDocumentsDescription': 'Start by uploading your medical studies and lab results to get personalized analysis.',
    'profile.uploadFirst': 'Upload my first document',
    'profile.noMatchingDocuments': 'No documents found',
    'profile.noMatchingDescription': 'No documents match the search criteria.',
    'profile.clearSearch': 'Clear search',
    'profile.fileName': 'File name',
    'profile.uploadDate': 'Upload date',
    'profile.fileSize': 'File size',
    'profile.actions': 'Actions',
    'profile.preview': 'Preview',
    'profile.download': 'Download',
    'profile.delete': 'Delete',
    'profile.confirmDelete': 'Delete document?',
    'profile.confirmDeleteDescription': 'This action cannot be undone. The document will be permanently deleted.',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Obtener idioma guardado del localStorage
    const saved = localStorage.getItem('evity-language') as Language;
    return saved || 'es'; // Español por defecto
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('evity-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}